name: CI

on:
  pull_request:
  push:
    branches: ["master"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Rust toolchain
      run: rustup default stable
    - name: Build
      run: cargo build --locked --verbose
    # - name: Run tests
    #  run: cargo test --locked --verbose
    - name: Rustfmt and Clippy
      run: |
        cargo fmt -- --check
        cargo clippy
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Setup Rust toolchain
      run: rustup default stable
    - name: Build
      run: cargo build --locked --verbose
    - name: Run example script
      run: cargo run -- --script ./demo/hello.lua --universe-id 28220420 --place-id 95206881 --oneshot
